### ISSUE TITLE
action_sync of task table throws AssertionError: duplicate key 

### ISSUE THREAD

**Issue by gflewis** [gflewis/sndml3#13]
<pre>
19:07:55 INFO [main] Generator GLOBAL INIT: dialect=pg schema=mittest namecase=LOWER namequotes=DOUBLE
19:07:55 INFO [main] Database GLOBAL INIT: SET TIME ZONE 'UTC'
19:07:55 INFO [main] LoaderConfig GLOBAL INIT: 
metrics: task.metrics
tables:
- {name: task, action: sync, partition: month}
19:07:57 INFO [main] RestTableAPI task PROCESS: getStats count=677389 query="sys_created_on<2020-01-07 19:07:55" createdRange=[2013-09-20 21:00:42,2020-01-07 19:07:01]
19:07:57 INFO [main] LoaderJob task INIT: partition=DatePartition[interval=MONTH size=77 min=2013-09-01 max=2020-02-01]
19:07:57 INFO [main] LoaderJob task INIT: begin sync task (677389 rows)
19:07:57 INFO [main] Synchronizer task.M2020-01-01 INIT: begin compare
Exception in thread "main" java.lang.AssertionError: duplicate key: 75f6096adb8a0c900b3573e1ba96195a
	at servicenow.datamart.Synchronizer.initialize(Synchronizer.java:69)
	at servicenow.datamart.Synchronizer.initialize(Synchronizer.java:39)
	at servicenow.api.DatePartitionedTableReader.call(DatePartitionedTableReader.java:142)
	at servicenow.api.DatePartitionedTableReader.call(DatePartitionedTableReader.java:15)
	at servicenow.datamart.LoaderJob.call(LoaderJob.java:126)
	at servicenow.datamart.Loader.loadTables(Loader.java:95)
	at servicenow.datamart.Loader.main(Loader.java:60)
[ec2-user@ip-172-31-42-132 mit]$ 
</pre>

**Comment by gflewis** [comment]
ACL related. Fixed in 3.1.0.
