### ISSUE TITLE
Connecting to Oracle ADW Database

### ISSUE THREAD

**Issue by yourreddy** [gflewis/sndml3#20]
Hi ,

Thanks for letting me use this product.
I am trying to set up a properties file to connect the Oracle ADW database. Getting the following error.

Any help will be appreciated.

**properties file.**

servicenow.instance=Dev564343
servicenow.username=testsync
servicenow.password=XXXXXXXXXXXXXXXXXXXXXXXX
datamart.url=jdbc:oracle:thin:@snowsyncpdb_medium?TNSADMIN=/home/opc/snowsync/sndml3/Wallet_SNOWSYNCDB/
datamart.username=admin
datamart.password=XXXXXXXXXXXXXXXXXXXXXXXX

**Error**

[opc@sarapp sndml3]$ java -jar sndml-3.0.2-ora.jar -p rc.properties -y /home/opc/rcsync/sndml3/RC/99-User/sys_user.yaml
23:29:23 INFO [main] Globals GLOBAL INIT: loadProperties /home/opc/rcsync/sndml3/rc.properties
23:29:23 INFO [main] Session GLOBAL INIT: instance=https://Dev564343.service-now.com/ user=rrreportdb
23:29:23 INFO [main] Database GLOBAL INIT: database=jdbc:oracle:thin:@snowsyncpdb_medium?TNSADMIN=/home/opc/rcsync/sndml3/Wallet_SNOWSYNCDB/ user=admin
Exception in thread "main" java.sql.SQLRecoverableException: IO Error: Invalid connection string format, a valid format is: "host:port:sid"
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:743)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:666)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:566)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at servicenow.datamart.Database.<init>(Database.java:48)
        at servicenow.datamart.Loader.main(Loader.java:42)
Caused by: oracle.net.ns.NetException: Invalid connection string format, a valid format is: "host:port:sid"
        at oracle.net.resolver.AddrResolution.resolveSimple(AddrResolution.java:554)
        at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:482)
        at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:595)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:230)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1452)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:496)
        ... 7 more
[opc@sarapp sndml3]$

Thanks
Raj

**Comment by gflewis** [comment]
I cannot help with specific Oracle JDBC connection issues. I can say that for Oracle I always use a thin connection and that the only 3 parameters are hostname, port and SID.  For example: "jdbc:oracle:thin:@myhost:1521:orcl".
