### ISSUE TITLE
assertion error using -t

### ISSUE THREAD

**Issue by gflewis** [gflewis/sndml3#3]
$ java -ea -jar $jar -t x_mppc2_intake_service_symptom -p xxxprodpg.profile
01:00:57 INFO [main] Globals GLOBAL INIT: loadProperties /home/ec2-user/sndml3/xxx/xxxprodpg.profile
01:00:57 INFO [main] Session GLOBAL INIT: instance=https://xxx.service-now.com/ user=xxxxxxxx
01:00:57 INFO [main] Database GLOBAL INIT: database=jdbc:postgresql://sndm-pg.cwp63xqkanus.us-east-2.rds.amazonaws.com:5432/sndm user=xxxxxx schema=xxx
01:00:57 INFO [main] Generator GLOBAL INIT: dialect=pg schema=xxx namecase=LOWER namequotes=DOUBLE
01:00:57 INFO [main] Database GLOBAL INIT: SET TIME ZONE 'UTC'
Exception in thread "main" java.lang.AssertionError
	at servicenow.datamart.Globals.getStart(Globals.java:92)
	at servicenow.datamart.DateTimeFactory.getStart(DateTimeFactory.java:52)
	at servicenow.datamart.JobConfig.getDefaultRange(JobConfig.java:252)
	at servicenow.datamart.JobConfig.getCreated(JobConfig.java:180)
	at servicenow.datamart.Job.call(Job.java:60)
	at servicenow.datamart.Loader.loadTables(Loader.java:95)
	at servicenow.datamart.Loader.main(Loader.java:51)

**Comment by gflewis** [comment]
Fixed in 3.0.2-SNAPSHOT
