### ISSUE TITLE
expected 'sys_id', found 'priority' in first column of table 'incident'

### ISSUE THREAD

**Issue by jonathangull** [gflewis/sndml3#33]
When trying to use upsert job (after Insert job created table in mssql successfully and has sys_id as first column) gives below error.

18:28:26 INFO Generator [DPRUN0001006]  INIT: dialect=mssql schema=dbo namecase=LOWER namequotes=SQUARE autocommit=false
Exception in thread "DPRUN0001006" java.lang.RuntimeException: expected 'sys_id', found 'priority' in first column of table 'incident'
        at sndml.datamart.ColumnDefinitions.<init>(ColumnDefinitions.java:67)
        at sndml.datamart.DatabaseTableWriter.open(DatabaseTableWriter.java:51)
        at sndml.datamart.DatabaseUpdateWriter.open(DatabaseUpdateWriter.java:24)
        at sndml.datamart.DatabaseUpdateWriter.open(DatabaseUpdateWriter.java:12)
        at sndml.datamart.JobRunner.runLoad(JobRunner.java:200)
        at sndml.datamart.JobRunner.call(JobRunner.java:99)
        at sndml.daemon.AppJobRunner.call(AppJobRunner.java:85)
        at sndml.daemon.AppJobRunner.run(AppJobRunner.java:60)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jonathangull** [comment]
Same is the case for sync as well. I can confirm the table is present and has sys_id as first column in target MSSQL database.

**Comment by jonathangull** [comment]
Thanks @gflewis looking at the error, it seems like SNDML is able to read the schema ( observe it says PRIORITY is the first column or contract is first column in below case) but the column order is not correct. 

Exception in thread "DPRUN0001012" java.lang.RuntimeException: expected 'sys_id', found 'contract' in first column of table 'sn_customerservice_case'
        at sndml.datamart.ColumnDefinitions.<init>(ColumnDefinitions.java:67)
        at sndml.datamart.DatabaseTableWriter.open(DatabaseTableWriter.java:51)
        
where is the configuration file for log4j, sorry I can't find it

**Comment by gflewis** [comment]
Here is another thought: I see that we are using mssql-jdbc version 8.2.2 (pom.xml line 122). I wonder if this issue would be fixed by upgrading the JDBC driver to 8.4.1?

**Comment by gflewis** [comment]
Here is an issue with a column order in the 8.2.2 driver:
https://github.com/microsoft/mssql-jdbc/issues/1332

**Comment by gflewis** [comment]
I would try upgrading the JDBC driver first. I think it looks like our issue. Do you have Maven installed, such that you can rebuild the JAR and see if it fixes the problem?

**Comment by jonathangull** [comment]
sorry I do not have. Struggling to rebuild the package after changing the version to       <version>8.4.1.jre8</version>.

can you please point me to instructions to rebuild

**Comment by gflewis** [comment]
First you need to install Apache Maven. If you are on a Mac, then I recommend you install it using HomeBrew. If you are on Windows or Linux then you may want to Google "install maven".

Then you go into the directory where you have cloned the repo. The file pom.xml should be in that directory. Then type this command:

mvn package

This should cause it to download all the necessary libraries and rebuild the JAR files in the target directory.

**Comment by jonathangull** [comment]
Thank you @gflewis after updating the jdbc driver, the column sys_id issue is gone. Thank you so much for unblocking me.

**Comment by gflewis** [comment]
Thank you @jonathangull for identifying this issue and testing the fix.
mssql-jdbc has been upgraded to 8.4.1 in v3.4.5
