### ISSUE TITLE
Transaction cancelled: maximum execution time exceeded 

### ISSUE THREAD

**Issue by jonathangull** [gflewis/sndml3#38]
I am trying to copy the task table using datapump, this time I have selected limited number of columns but get this error. I would really like datapump to skip the error records and continue instead of hard failure, is it not possible to configure?

"error":{"message":"Transaction cancelled: maximum execution time exceeded","detail":"Transaction cancelled: maximum execution time exceeded Check logs for error trace or enable glide.rest.debug property to verify REST request processing"},"status":"failure"}
Exception in thread "DPRUN0001020" java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.TextNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.TextNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader 'app')
        at sndml.servicenow.RecordList.<init>(RecordList.java:30)
        at sndml.servicenow.RestTableAPI.getRecords(RestTableAPI.java:116)
        at sndml.servicenow.RestTableReader.call(RestTableReader.java:76)
        at sndml.datamart.JobRunner.runLoad(JobRunner.java:223)
        at sndml.datamart.JobRunner.call(JobRunner.java:99)
        at sndml.daemon.AppJobRunner.call(AppJobRunner.java:85)
        at sndml.daemon.AppJobRunner.run(AppJobRunner.java:60)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by gflewis** [comment]
This error indicates that the REST query was two large, and a timeout occurred. The **Partition** option on the **Advanced** tab of the **Job** form will cause SNDML to chop the large query into multiple small queries, and it should fix the problem. Please set the **Partition** to "Week" and try again. Let me know if this works.

**Comment by jonathangull** [comment]
Hi @gflewis apologies for delay, using partition has helped resolve this. Thank you.
